### ISSUE TITLE
How to process new images?

### ISSUE THREAD

**Issue by MoHanWant2See** [ivanDonadello/Visual-Relationship-Detection_LTN#1]
Hi,

Thanks for the code. 

I can run the scripts predicate_detection_LTN.m and relationship_phrase_detection_LTN.m and see the results, but how can i use the pre-trained model to process new images and get the triples (subject, relation, object) ? 

Thanks !

**Comment by ivanDonadello** [comment]
Dear MoHanWant2See,

as pre-trained model I used the original one in the paper provided here https://github.com/Prof-Lu-Cewu/Visual-Relationship-Detection/tree/master/data. However, the authors provided only the bounding boxes.

**Comment by MoHanWant2See** [comment]
Thanks for reply！

**Comment by ivanDonadello** [comment]
You're welcome!

**Comment by alice-cool** [comment]
Dear scholar,
        the code can detect new image's relationship type?

**Comment by ivanDonadello** [comment]
Dear @alice-cool,

if you mean a new relationship type such as "jump over" the answer is no because "jump over" is outside of the dataset vocabulary. If you mean a new visual relationship such as (man, ride, elephant) never seen during training but with all the terms in the dataset vocabulary the answer is yes, this is the so-called _zero-shot learning_.

**Comment by alice-cool** [comment]
Dear scholar,
Thanks for your reply.  I want to know in your project whether exists the **object detection model** to  extract the features not only using the pretrained features matrix from  https://github.com/Prof-Lu-Cewu/Visual-Relationship-Detection/tree/master/data
 file to train the visual detection.

**Comment by ivanDonadello** [comment]
We only used the already given bounding boxes provided by the [authors](https://github.com/Prof-Lu-Cewu/Visual-Relationship-Detection/blob/master/data/objectDetRCNN.mat). This allowed us a fair comparison with the other competitors.
