### ISSUE TITLE
what's the structure of data in predicates.csv and types.cs?

### ISSUE THREAD

**Issue by Tord-Zhang** [ivanDonadello/Visual-Relationship-Detection_LTN#2]
what's the meaning of each row in these two files?
in predicates.csv:

`1.000000000000000000e+00,0.000000000000000000e+00,3.400000000000000000e+01
3.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00
3.000000000000000000e+00,0.000000000000000000e+00,3.400000000000000000e+01
4.000000000000000000e+00,0.000000000000000000e+00,3.400000000000000000e+01
4.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00`

and in types.csv

`1.300000000000000000e+01
1.000000000000000000e+00
1.100000000000000000e+01
1.000000000000000000e+00
1.000000000000000000e+00
3.700000000000000000e+01
1.000000000000000000e+00
7.000000000000000000e+00
2.800000000000000000e+01
3.400000000000000000e+01
1.700000000000000000e+01
1.000000000000000000e+00
1.700000000000000000e+01
7.000000000000000000e+00`

**Comment by ivanDonadello** [comment]
Dear @mangdian,

predicates.csv contains triples (subject_id, object_id, relationship_id) such as subject/object_id is the bounding box id contained in features.csv, that is subject/object_id is the number of the line in features.csv. Each line in features.csv represents a bounding box.

Each line of types.csv contains the class of the bounding box in the corresponding line, that is, the first bb has class/type 13. I hope that this answers you.

**Comment by Tord-Zhang** [comment]
But the detection scores in features.csv already indicates the type of each bounding box, why do we need the type.CSV?

**Comment by ivanDonadello** [comment]
Type.csv is the ground truth and you can use it as a feature with a one-hot encoder. The detection score is a proposal score coming from the Fast-RCNN object detector and sometimes the maximum does not agree with the type in type.csv. You can use these features to check if LTNs work better.

**Comment by Tord-Zhang** [comment]
@ivanDonadello Hi, thanks for your help! I got another question. The shape of the object bbox mat saved for evalation is 1000 x 940 x 4。what does "940" mean?
