### ISSUE TITLE
Test image doesn't exist

### ISSUE THREAD

**Issue by jyhong0304** [ivanDonadello/Visual-Relationship-Detection_LTN#3]
After a model was trained using train.py, I tried to run preciate_detection.py but got the following error:

`IOError: [Errno 2] No such file or directory: u'DIRECTORY_PATH/Visual-Relationship-Detection-LTN/data/sg_test_images/4806585594_f8a9f49577_b.jpg'
`

The 'sg_test_images' you provided and 'imagePath.mat' do not seem to match.
Where can I find the dataset?

**Comment by ivanDonadello** [comment]
I uploaded the missing image but I think another one is missing. Could you please try again and write me the other image name?

**Comment by jyhong0304** [comment]
Yes, I got another error indicating the missing file as follows:

`IOError: [Errno 2] No such file or directory: u'DIRECTORY_PATH/Visual-Relationship-Detection-LTN/data/sg_test_images/5564918619_bdb87d2833_b.jpg'
`

**Comment by ivanDonadello** [comment]
Should be fixed now. Sorry for the problem.

**Comment by jyhong0304** [comment]
It worked perfectly! Thank you so much!
