### ISSUE TITLE
can't access your dataset

### ISSUE THREAD

**Issue by xywhat** [ivanDonadello/Visual-Relationship-Detection_LTN#4]
it seems that my count is not on your list.

**Comment by petneli** [comment]
Hi, @ivanDonadello, can you please again share a link to the LTN encoding of the VRD dataset. The sharepoint link doesn't seem to work anymore. Thanks a lot!

**Comment by ivanDonadello** [comment]
Dear @petneli, now the links should work again. Sorry for the annoyance.

**Comment by xywhat** [comment]
> Hi, @ivanDonadello, can you please again share a link to the LTN encoding of the VRD dataset. The sharepoint link doesn't seem to work anymore. Thanks a lot!

hi! Sorry to bother you. Could you share me the paper of this code, I cant find it anyway.
